apiVersion: v1
kind: ReplicationController
metadata:
  name: products-rc
spec:
  replicas: 2
  selector:
    app: products
    version: "1.0"
  template:
    metadata:
      labels:
        app: products
        version: "1.0"
    spec:
      containers:
      - name: product-service
        image: product-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
