apiVersion: v1
kind: Service
metadata:
  name: products-svc
spec:
  selector:
    app: products
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8010
    nodePort: 30036
    protocol: TCP
