version: 2
jobs:
  build:
    working_directory: ~/springboot-docker-K8s
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    steps:
      - checkout

      - restore_cache:
          key: springboot-docker-K8s-{{ checksum "pom.xml" }}

      - run: mvn clean package

      - save_cache:
          paths:
            - ~/.m2
          key: springboot-docker-K8s-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/app.jar